import type { NewsArticle, NewsCategory, IndianState } from '@/types';

const src = {
  ndtv:   { id: 'ndtv',   name: 'NDTV',            url: 'https://ndtv.com' },
  toi:    { id: 'toi',    name: 'Times of India',   url: 'https://timesofindia.com' },
  hindu:  { id: 'hindu',  name: 'The Hindu',        url: 'https://thehindu.com' },
  et:     { id: 'et',     name: 'Economic Times',   url: 'https://economictimes.com' },
  it:     { id: 'it',     name: 'India Today',      url: 'https://indiatoday.in' },
  ht:     { id: 'ht',     name: 'Hindustan Times',  url: 'https://hindustantimes.com' },
  mint:   { id: 'mint',   name: 'Mint',             url: 'https://livemint.com' },
  ie:     { id: 'ie',     name: 'Indian Express',   url: 'https://indianexpress.com' },
  wion:   { id: 'wion',   name: 'WION',             url: 'https://wionews.com' },
  deccan: { id: 'deccan', name: 'Deccan Herald',    url: 'https://deccanherald.com' },
};

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo  = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const MOCK_ARTICLES: NewsArticle[] = [
  // ─── MAHARASHTRA ───────────────────────────────────────────────────────────
  {
    id: 'mh-001',
    title: 'Mumbai Metro Line 3 Full Operational: Record 8 Lakh Daily Riders in First Week',
    description: 'The underground Aqua Line connecting Aarey to Cuffe Parade has transformed Mumbai commuting, cutting travel time from 75 to 40 minutes.',
    summary: 'Mumbai Metro Line 3 crosses 8 lakh daily riders milestone, easing commute across the 33.5 km Aqua Line.',
    aiSummary: "Mumbai's underground Metro Line 3 (Aqua Line) achieved unprecedented ridership of 8 lakh commuters per day in its inaugural full week. This infrastructure milestone reduces the Aarey-to-Cuffe Parade journey from 75 to 40 minutes, decongesting major arterial roads. The ₹33,406 crore project is expected to remove 4.5 lakh cars from Mumbai roads annually.",
    source: src.toi,
    category: 'government',
    state: 'Maharashtra',
    city: 'Mumbai',
    coordinates: { lat: 19.0760, lng: 72.8777 },
    publishedAt: hoursAgo(2),
    imageUrl: 'https://picsum.photos/seed/mh001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.82,
    impactScore: { local: 95, state: 80, national: 60, global: 15 },
    tags: ['Mumbai', 'Metro', 'Infrastructure', 'Transport', 'Maharashtra'],
    isBreaking: true,
    viewCount: 45230,
  },
  {
    id: 'mh-002',
    title: 'Pune Startup Ecosystem Sees ₹4,200 Crore VC Investment in Q1 2025',
    description: "Pune's tech startup scene is booming with major investments in SaaS, fintech, and deeptech sectors.",
    summary: 'Pune attracts ₹4,200 crore in VC investment in Q1 2025, cementing its position as India\'s third-largest startup hub.',
    aiSummary: "Pune's startup ecosystem attracted ₹4,200 crore in venture capital during Q1 2025, outpacing traditional hubs. Key sectors include B2B SaaS, fintech infrastructure, and deep tech. The Maharashtra government's Pune Startup Hub initiative combined with proximity to Bengaluru talent pools has positioned the city as a formidable third pillar of India's innovation economy.",
    source: src.et,
    category: 'startups',
    state: 'Maharashtra',
    city: 'Pune',
    coordinates: { lat: 18.5204, lng: 73.8567 },
    publishedAt: hoursAgo(5),
    imageUrl: 'https://picsum.photos/seed/mh002/800/400',
    sentiment: 'positive',
    sentimentScore: 0.75,
    impactScore: { local: 85, state: 90, national: 70, global: 40 },
    tags: ['Pune', 'Startups', 'Venture Capital', 'Technology', 'Maharashtra'],
    isBreaking: false,
    viewCount: 23400,
  },
  {
    id: 'mh-003',
    title: 'Maharashtra CM Announces ₹15,000 Crore Agricultural Relief for Drought-Hit Farmers',
    description: 'Following worst drought in 30 years, Maharashtra declares emergency relief covering 12 districts across Marathwada and Vidarbha.',
    summary: 'Maharashtra announces ₹15,000 crore drought relief for 38 lakh farmers across Marathwada and Vidarbha.',
    aiSummary: "The Maharashtra government declared a ₹15,000 crore agricultural relief package addressing the worst drought in three decades. Relief covers 38 lakh farmers across Marathwada and Vidarbha, including ₹6,000 direct transfer per acre, crop loan moratoriums, and emergency water tankers. Environmental experts warn groundwater depletion is the underlying structural issue requiring long-term policy intervention.",
    source: src.ndtv,
    category: 'government',
    state: 'Maharashtra',
    city: 'Nagpur',
    coordinates: { lat: 21.1458, lng: 79.0882 },
    publishedAt: hoursAgo(8),
    imageUrl: 'https://picsum.photos/seed/mh003/800/400',
    sentiment: 'neutral',
    sentimentScore: -0.10,
    impactScore: { local: 98, state: 95, national: 65, global: 20 },
    tags: ['Maharashtra', 'Drought', 'Agriculture', 'Farmers', 'Relief'],
    isBreaking: true,
    viewCount: 67890,
  },

  // ─── DELHI ─────────────────────────────────────────────────────────────────
  {
    id: 'dl-001',
    title: "Delhi AQI Improves to 'Moderate' as Winter Pollution Task Force Shows Results",
    description: "Sustained enforcement of anti-pollution measures brings Delhi's AQI to a 5-year low for this season.",
    summary: "Delhi AQI reaches 5-year seasonal low of 85 ('Moderate') as multi-agency pollution control measures yield results.",
    aiSummary: "Delhi achieved a significant air quality milestone with AQI readings in the Moderate category (85), best performance in 5 years. Improvements stem from: satellite-monitored stubble burning reduction in Punjab (down 42%), stricter vehicular emission checks, and GRAP enforcement. Experts caution sustained improvement requires structural changes to agricultural and industrial emissions.",
    source: src.hindu,
    category: 'government',
    state: 'Delhi',
    city: 'New Delhi',
    coordinates: { lat: 28.6139, lng: 77.2090 },
    publishedAt: hoursAgo(3),
    imageUrl: 'https://picsum.photos/seed/dl001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.65,
    impactScore: { local: 98, state: 95, national: 60, global: 35 },
    tags: ['Delhi', 'Air Quality', 'AQI', 'Pollution', 'Environment'],
    isBreaking: false,
    viewCount: 89000,
  },
  {
    id: 'dl-002',
    title: 'Supreme Court Orders NTA to Re-Conduct NEET-UG Exam After Paper Leak Evidence',
    description: "India's apex court rules in favour of petitioners after widespread paper leak affecting 23 lakh students.",
    summary: 'Supreme Court orders fresh NEET-UG exam within 45 days after paper leak evidence, impacting 23 lakh medical aspirants.',
    aiSummary: "The Supreme Court directed NTA to re-conduct NEET-UG 2025 within 45 days after forensic evidence confirmed systematic paper leaks originating from Patna and Hazaribagh. The court ordered CBI investigation, interim protection for students who joined colleges provisionally, and evaluation of compensation for affected aspirants. The ruling is expected to trigger comprehensive reforms to India's centralized medical entrance examination system.",
    source: src.ie,
    category: 'education',
    state: 'Delhi',
    city: 'New Delhi',
    coordinates: { lat: 28.6304, lng: 77.2177 },
    publishedAt: hoursAgo(6),
    imageUrl: 'https://picsum.photos/seed/dl002/800/400',
    sentiment: 'negative',
    sentimentScore: -0.55,
    impactScore: { local: 85, state: 80, national: 98, global: 30 },
    tags: ['NEET', 'Supreme Court', 'Education', 'NTA', 'Students'],
    isBreaking: true,
    viewCount: 156000,
  },
  {
    id: 'dl-003',
    title: 'India-US Tech Partnership Summit: $50 Billion Investment in Semiconductor Fabs Announced',
    description: 'Joint venture to establish India\'s first advanced semiconductor fabrication facilities in Delhi-NCR and Gujarat.',
    summary: '$50 billion semiconductor fab investment announced at India-US summit, with facilities in Delhi-NCR and Gujarat\'s Dholera.',
    aiSummary: "A watershed moment for India's technology ambitions: the India-US Tech Partnership Summit unlocked $50 billion in semiconductor manufacturing commitments. ISMC's joint venture with Intel targets 28nm node chips in Greater Noida by 2027, while Micron's Dholera facility will produce advanced DRAM. The investment is expected to create 85,000 direct and 3.5 lakh indirect jobs, positioning India to capture 12% of global chip production by 2030.",
    source: src.mint,
    category: 'technology',
    state: 'Delhi',
    city: 'New Delhi',
    coordinates: { lat: 28.5245, lng: 77.3350 },
    publishedAt: hoursAgo(1),
    imageUrl: 'https://picsum.photos/seed/dl003/800/400',
    sentiment: 'positive',
    sentimentScore: 0.90,
    impactScore: { local: 75, state: 70, national: 99, global: 90 },
    tags: ['Semiconductor', 'Technology', 'India-US', 'Investment', 'Manufacturing'],
    isBreaking: true,
    viewCount: 203000,
  },

  // ─── KARNATAKA ─────────────────────────────────────────────────────────────
  {
    id: 'ka-001',
    title: 'Bengaluru Startup Ather Energy IPO Subscribed 47x, Raises ₹3,100 Crore',
    description: 'Electric vehicle startup Ather Energy\'s mega IPO sees overwhelming investor response, valuing the company at ₹22,000 crore.',
    summary: 'Ather Energy IPO subscribed 47x, raising ₹3,100 crore — largest EV startup listing in India.',
    aiSummary: "Ather Energy's landmark IPO, subscribed 47 times, is the most successful EV company listing in India to date. The ₹3,100 crore raised will fund 8 new manufacturing facilities and expansion to 200 additional cities. With 1.8 lakh scooters sold in FY2024, Ather is positioning itself to challenge Ola Electric's market leadership. The listing reflects investor confidence in India's EV transition narrative, with 2-wheeler EV penetration expected to hit 30% by 2028.",
    source: src.mint,
    category: 'startups',
    state: 'Karnataka',
    city: 'Bengaluru',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    publishedAt: hoursAgo(4),
    imageUrl: 'https://picsum.photos/seed/ka001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.88,
    impactScore: { local: 85, state: 90, national: 85, global: 55 },
    tags: ['Ather Energy', 'IPO', 'EV', 'Startups', 'Bengaluru'],
    isBreaking: false,
    viewCount: 134500,
  },
  {
    id: 'ka-002',
    title: 'Bengaluru Water Crisis: BWSSB Announces 3-Day Rotation as Kaveri Levels Drop',
    description: 'Kaveri river flows at 30-year low as Bengaluru implements emergency water rationing affecting 1.2 crore residents.',
    summary: 'BWSSB announces emergency water rationing for 1.2 crore Bengaluru residents as Kaveri hits 30-year low inflows.',
    aiSummary: "Bengaluru faces its most severe water crisis in decades with Kaveri river flows at a 30-year low due to poor monsoon in Kodagu. BWSSB implemented emergency rationing: alternate-day supply for South/Central Bengaluru, 3-day rotation for Northern zones. The city's 1.35 crore population has exacerbated structural water supply gaps. Rapid concretization blocking groundwater recharge is a compounding factor. Karnataka has invoked the Inter-State Water Disputes Act seeking emergency reservoir releases.",
    source: src.deccan,
    category: 'government',
    state: 'Karnataka',
    city: 'Bengaluru',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    publishedAt: hoursAgo(7),
    imageUrl: 'https://picsum.photos/seed/ka002/800/400',
    sentiment: 'negative',
    sentimentScore: -0.70,
    impactScore: { local: 99, state: 85, national: 55, global: 20 },
    tags: ['Bengaluru', 'Water Crisis', 'BWSSB', 'Kaveri', 'Karnataka'],
    isBreaking: true,
    viewCount: 178900,
  },
  {
    id: 'ka-003',
    title: "ISRO Launches India's First Space Docking Experiment — SpaDeX Mission Success",
    description: 'ISRO achieves historic in-space docking technology demonstration, making India the 4th nation to master the capability.',
    summary: "ISRO's SpaDeX mission achieves India's first autonomous space docking — India becomes 4th nation with this critical capability.",
    aiSummary: "India achieved a historic space milestone with ISRO's SpaDeX successfully demonstrating autonomous in-orbit docking. The SDX01 and SDX02 satellites rendezvous and dock autonomously at 470km altitude, validating Indian-developed algorithms. This capability is foundational for Chandrayaan-4 lunar sample return, the Bharatiya Antariksha Station, and crewed Gaganyaan follow-up missions. The mission was completed at a fraction of comparable international programs, showcasing ISRO's cost efficiency.",
    source: src.ndtv,
    category: 'science',
    state: 'Karnataka',
    city: 'Bengaluru',
    coordinates: { lat: 13.0337, lng: 80.2707 },
    publishedAt: hoursAgo(10),
    imageUrl: 'https://picsum.photos/seed/ka003/800/400',
    sentiment: 'positive',
    sentimentScore: 0.95,
    impactScore: { local: 70, state: 75, national: 99, global: 95 },
    tags: ['ISRO', 'SpaDeX', 'Space', 'Science', 'India'],
    isBreaking: true,
    viewCount: 245000,
  },

  // ─── TAMIL NADU ─────────────────────────────────────────────────────────────
  {
    id: 'tn-001',
    title: 'Chennai Floods: IMD Issues Red Alert as Cyclone Fengal Remnants Dump 40cm Rain',
    description: 'Remnant low pressure from Cyclone Fengal causes catastrophic flooding in Chennai, Cuddalore, and Villupuram.',
    summary: 'Chennai faces catastrophic flooding as Cyclone Fengal remnants bring 40cm rain; red alert for Chennai, Cuddalore, Villupuram.',
    aiSummary: "Cyclone Fengal's remnant triggered the worst flooding in Chennai since 2021. The city received 40cm rainfall in 24 hours — 60% of annual average. Key roads including ECR, OMR, and GST Road are submerged. NDRF and TNSDMA deployed 45 rescue teams. Airport operations suspended 48 hours. Tamil Nadu declared a state of disaster and requested ₹5,000 crore from NDRF.",
    source: src.hindu,
    category: 'weather',
    state: 'Tamil Nadu',
    city: 'Chennai',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    publishedAt: hoursAgo(1),
    imageUrl: 'https://picsum.photos/seed/tn001/800/400',
    sentiment: 'negative',
    sentimentScore: -0.85,
    impactScore: { local: 99, state: 95, national: 70, global: 35 },
    tags: ['Chennai', 'Floods', 'Cyclone', 'IMD', 'Tamil Nadu'],
    isBreaking: true,
    viewCount: 312000,
  },
  {
    id: 'tn-002',
    title: 'Tamil Nadu Tops EV Adoption: 3.8 Lakh Electric Vehicles Registered in 2024-25',
    description: 'Tamil Nadu leads all Indian states in EV registration growth, driven by policy incentives and charging infrastructure.',
    summary: 'Tamil Nadu leads India with 3.8 lakh EV registrations in FY25, driven by zero road tax and 8,000 charging stations.',
    aiSummary: "Tamil Nadu emerged as India's EV adoption leader with 3.8 lakh registrations in FY2024-25, surpassing Maharashtra and Karnataka. Key policy drivers: zero road tax on EVs, ₹5,000 subsidy per two-wheeler EV, and 8,000 public charging stations via TN EV Policy 2023. Hyundai's EV plant in Sriperumbudur and TVS Motor's new EV facility in Hosur strengthen the supply chain.",
    source: src.et,
    category: 'technology',
    state: 'Tamil Nadu',
    city: 'Chennai',
    coordinates: { lat: 12.9000, lng: 80.1000 },
    publishedAt: daysAgo(1),
    imageUrl: 'https://picsum.photos/seed/tn002/800/400',
    sentiment: 'positive',
    sentimentScore: 0.78,
    impactScore: { local: 85, state: 92, national: 75, global: 40 },
    tags: ['Tamil Nadu', 'EV', 'Electric Vehicles', 'Sustainability', 'Policy'],
    isBreaking: false,
    viewCount: 67200,
  },

  // ─── UTTAR PRADESH ──────────────────────────────────────────────────────────
  {
    id: 'up-001',
    title: 'Maha Kumbh 2025: Over 45 Crore Pilgrims — A New World Record',
    description: 'The Maha Kumbh Mela 2025 in Prayagraj sets new world record as the largest peaceful human gathering in recorded history.',
    summary: '45 crore pilgrims attend Maha Kumbh 2025 at Prayagraj — new world record for largest peaceful gathering in history.',
    aiSummary: "Maha Kumbh 2025 set a world record with 45 crore pilgrims attending over 45 days. The UP government deployed 40,000 police, 50 NDRF teams, and an AI-powered crowd management system across 4,000 hectares. Economic impact on Prayagraj and surroundings is estimated at ₹1.2 lakh crore, with delegations from 162 countries marking the event as a global cultural phenomenon.",
    source: src.toi,
    category: 'government',
    state: 'Uttar Pradesh',
    city: 'Prayagraj',
    coordinates: { lat: 25.4358, lng: 81.8463 },
    publishedAt: daysAgo(2),
    imageUrl: 'https://picsum.photos/seed/up001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.92,
    impactScore: { local: 99, state: 98, national: 99, global: 90 },
    tags: ['Maha Kumbh', 'Prayagraj', 'World Record', 'Uttar Pradesh', 'Religion'],
    isBreaking: false,
    viewCount: 678000,
  },
  {
    id: 'up-002',
    title: 'Lucknow IT City: TCS, Infosys, Wipro Set Up Campuses in ₹8,500 Crore Tech Corridor',
    description: 'Uttar Pradesh government signs MoUs with India\'s top IT companies to develop 500-acre technology park near Lucknow Airport.',
    summary: 'TCS, Infosys, Wipro to set up Lucknow campuses in ₹8,500 crore IT corridor, creating 1.5 lakh jobs in Uttar Pradesh.',
    aiSummary: "Uttar Pradesh is executing its most ambitious economic diversification with the ₹8,500 crore Lucknow IT City project. TCS sets up 3M sq ft, Infosys 2.5M sq ft, and Wipro a mixed-use tech park. Targets 1.5 lakh direct IT and 4 lakh indirect jobs. UP's improved law-and-order track record and Expressway connectivity were key factors in attracting investments.",
    source: src.ht,
    category: 'business',
    state: 'Uttar Pradesh',
    city: 'Lucknow',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    publishedAt: hoursAgo(12),
    imageUrl: 'https://picsum.photos/seed/up002/800/400',
    sentiment: 'positive',
    sentimentScore: 0.85,
    impactScore: { local: 90, state: 95, national: 75, global: 35 },
    tags: ['Lucknow', 'IT', 'TCS', 'Infosys', 'Uttar Pradesh', 'Jobs'],
    isBreaking: false,
    viewCount: 89400,
  },

  // ─── WEST BENGAL ────────────────────────────────────────────────────────────
  {
    id: 'wb-001',
    title: "Kolkata Metro East-West Corridor: India's First Underwater Metro Opens",
    description: 'India\'s first underwater metro passes beneath the Hooghly River, connecting Howrah Maidan to Esplanade.',
    summary: "Kolkata opens India's first underwater metro — 502m tunnel beneath Hooghly River connecting Howrah to Esplanade.",
    aiSummary: "India inaugurated its first underwater metro at Kolkata — a 502-meter tunnel beneath the Hooghly River at 13 meters depth. The East-West Metro corridor now fully connects Howrah Maidan to Sector V, 16.6 km with 12 stations. KMRC used world's most advanced TBM technology. The underwater stretch was engineered to withstand tidal pressure and seismic activity up to magnitude 8.0, setting new benchmarks for Indian infrastructure.",
    source: src.toi,
    category: 'government',
    state: 'West Bengal',
    city: 'Kolkata',
    coordinates: { lat: 22.5726, lng: 88.3639 },
    publishedAt: hoursAgo(9),
    imageUrl: 'https://picsum.photos/seed/wb001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.88,
    impactScore: { local: 95, state: 88, national: 70, global: 40 },
    tags: ['Kolkata', 'Metro', 'Infrastructure', 'Hooghly', 'West Bengal'],
    isBreaking: false,
    viewCount: 112300,
  },

  // ─── GUJARAT ────────────────────────────────────────────────────────────────
  {
    id: 'gj-001',
    title: 'Reliance Jio GigaFiber Launches 10 Gbps Home Broadband at ₹999/Month in Ahmedabad',
    description: "Jio's revolutionary 10 Gbps fiber-to-home service goes live in Ahmedabad as pilot.",
    summary: "Jio launches India's first 10 Gbps home broadband in Ahmedabad at ₹999/month, disrupting home internet market.",
    aiSummary: "Reliance Jio's GigaFiber 10 Gbps launch marks a quantum leap in India's home broadband. The service using GPON+XGS-PON fiber offers symmetrical 10 Gbps at ₹2,999/month — a global benchmark for price-per-Gbps. Pilot covers 15 lakh Ahmedabad homes, expanding to 100 cities by Q3 2025. Expected to trigger broadband price war among Airtel, BSNL, and ACT Fibernet, benefiting consumers across urban India.",
    source: src.et,
    category: 'technology',
    state: 'Gujarat',
    city: 'Ahmedabad',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    publishedAt: hoursAgo(6),
    imageUrl: 'https://picsum.photos/seed/gj001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.80,
    impactScore: { local: 88, state: 82, national: 85, global: 45 },
    tags: ['Jio', 'Broadband', 'Internet', 'Gujarat', 'Technology'],
    isBreaking: false,
    viewCount: 145000,
  },
  {
    id: 'gj-002',
    title: 'Vibrant Gujarat Summit: ₹27 Lakh Crore in Investment Proposals from 111 Countries',
    description: 'Gandhinagar hosts the global Vibrant Gujarat Summit with record investment pledges spanning manufacturing, green energy, and AI.',
    summary: 'Vibrant Gujarat Summit 2025 attracts ₹27 lakh crore in investment from 111 countries — India\'s largest ever business summit.',
    aiSummary: "The 11th Vibrant Gujarat Global Summit set a record with ₹27 lakh crore in investment proposals — 3x the previous edition. Key mega-investments include $15 billion green hydrogen plant by L&T and TotalEnergies, $8 billion semiconductor packaging by Tata Electronics, and $5 billion AI compute cluster by Adani AI. 111 countries participated with US, UAE, and Japan as largest investors. Implementation of 40% of pledged investments would add 2.3% to Gujarat's state GDP.",
    source: src.ie,
    category: 'business',
    state: 'Gujarat',
    city: 'Gandhinagar',
    coordinates: { lat: 23.2156, lng: 72.6369 },
    publishedAt: daysAgo(1),
    imageUrl: 'https://picsum.photos/seed/gj002/800/400',
    sentiment: 'positive',
    sentimentScore: 0.92,
    impactScore: { local: 90, state: 97, national: 95, global: 80 },
    tags: ['Vibrant Gujarat', 'Investment', 'Business', 'Gujarat', 'Economy'],
    isBreaking: false,
    viewCount: 234000,
  },

  // ─── RAJASTHAN ──────────────────────────────────────────────────────────────
  {
    id: 'rj-001',
    title: "Rajasthan's 30 GW Bhadla Solar Expansion to Power 2 Crore Homes",
    description: "Asia's largest solar park at Bhadla undergoes massive expansion to become world's largest renewable energy facility.",
    summary: 'Rajasthan approves 30 GW Bhadla Solar Park expansion worth ₹1.2 lakh crore — set to be world\'s largest renewable facility.',
    aiSummary: "Rajasthan is set to become the renewable energy capital of the world with the approved 30 GW expansion of Bhadla Solar Park. The ₹1.2 lakh crore project brings total capacity to 40 GW, includes a dedicated green hydrogen zone (1 million tonnes annually), and a 2,000 km HVDC line enabling surplus export to Bangladesh. The project generates 75,000 construction jobs and 12,000 permanent technical positions.",
    source: src.mint,
    category: 'science',
    state: 'Rajasthan',
    city: 'Jodhpur',
    coordinates: { lat: 27.9606, lng: 72.4600 },
    publishedAt: hoursAgo(14),
    imageUrl: 'https://picsum.photos/seed/rj001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.85,
    impactScore: { local: 88, state: 95, national: 90, global: 75 },
    tags: ['Rajasthan', 'Solar', 'Renewable Energy', 'Bhadla', 'Green Energy'],
    isBreaking: false,
    viewCount: 123400,
  },

  // ─── TELANGANA ──────────────────────────────────────────────────────────────
  {
    id: 'tl-001',
    title: 'Hyderabad Overtakes Bengaluru in Tech Talent Hiring: 2.4 Lakh Jobs Added in 2024',
    description: 'Hyderabad\'s tech sector surpasses Bengaluru in new job creation, with Microsoft, Google, and Amazon scaling up.',
    summary: 'Hyderabad tops Bengaluru in tech job creation with 2.4 lakh new positions in 2024 as Microsoft, Google, Amazon scale up.',
    aiSummary: "Hyderabad surpassed Bengaluru in technology sector job creation for the first time. The 2.4 lakh new tech jobs span software development, AI/ML, cloud infrastructure, and cybersecurity. Microsoft's Hyderabad campus expansion by 1.5M sq ft is India's largest corporate real estate expansion in 2024. Telangana's proactive T-IPASS policy and comparatively lower cost of living have made Hyderabad increasingly attractive to MNCs relocating from Bengaluru.",
    source: src.ht,
    category: 'technology',
    state: 'Telangana',
    city: 'Hyderabad',
    coordinates: { lat: 17.3850, lng: 78.4867 },
    publishedAt: hoursAgo(5),
    imageUrl: 'https://picsum.photos/seed/tl001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.82,
    impactScore: { local: 92, state: 95, national: 80, global: 55 },
    tags: ['Hyderabad', 'Technology', 'Jobs', 'IT', 'Telangana'],
    isBreaking: false,
    viewCount: 167800,
  },

  // ─── KERALA ─────────────────────────────────────────────────────────────────
  {
    id: 'kl-001',
    title: "Kerala Becomes India's First Carbon-Neutral State for Government Operations",
    description: 'Kerala achieves landmark carbon neutrality through 100% renewable energy, EV fleets, and forest carbon credits.',
    summary: "Kerala becomes India's first carbon-neutral state for government operations through renewable energy, EV fleet, and forest credits.",
    aiSummary: "Kerala's carbon neutrality covers all 14 departments, 140 government buildings, and 8,500 government vehicles. The state installed 45 MW rooftop solar, converted 8,500 vehicles to electric, and verified 3.2 million tonnes of forest carbon credits from the Western Ghats. Certified under PAS 2060 international standard. This positions Kerala for international climate finance access and eco-tourism branding worth ₹15,000 crore annually.",
    source: src.hindu,
    category: 'government',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    coordinates: { lat: 8.5241, lng: 76.9366 },
    publishedAt: hoursAgo(11),
    imageUrl: 'https://picsum.photos/seed/kl001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.90,
    impactScore: { local: 90, state: 97, national: 85, global: 80 },
    tags: ['Kerala', 'Carbon Neutral', 'Environment', 'Climate', 'Green Energy'],
    isBreaking: false,
    viewCount: 234500,
  },
  {
    id: 'kl-002',
    title: 'Nipah Virus Outbreak Contained in Kerala\'s Kozhikode: 3 Cases, 1 Death',
    description: "Kerala's health machinery activates rapid containment protocol, isolating 1,200 contacts after Nipah cluster.",
    summary: "Kerala contains Nipah cluster in Kozhikode — 3 cases, 1 death, 1,200 contacts traced; WHO monitoring situation.",
    aiSummary: "Kerala's early Nipah detection in Kozhikode demonstrates the state's world-class epidemiological response capability. Rapid tracing of 1,200 individuals within 36 hours, mobile BSL-3 testing units, and dedicated Nipah wards at Kozhikode Medical College have so far prevented community spread. WHO commended Kerala's response and is dispatching a technical advisory team. The 33% case fatality rate underscores Nipah's lethality and importance of early detection.",
    source: src.ndtv,
    category: 'health',
    state: 'Kerala',
    city: 'Kozhikode',
    coordinates: { lat: 11.2588, lng: 75.7804 },
    publishedAt: hoursAgo(4),
    imageUrl: 'https://picsum.photos/seed/hl002/800/400',
    sentiment: 'negative',
    sentimentScore: -0.65,
    impactScore: { local: 95, state: 90, national: 75, global: 65 },
    tags: ['Nipah', 'Kerala', 'Health', 'Outbreak', 'Kozhikode'],
    isBreaking: true,
    viewCount: 234000,
  },

  // ─── MADHYA PRADESH ─────────────────────────────────────────────────────────
  {
    id: 'mp-001',
    title: "Madhya Pradesh Tiger Population Crosses 1,000 — India's Biggest Wildlife Victory",
    description: "MP's tiger reserves report a census of 1,008 tigers — 25% of India's entire tiger population.",
    summary: "Madhya Pradesh becomes first Indian state with 1,000+ tigers — 26% of India's total.",
    aiSummary: "Madhya Pradesh's tiger population crossing 1,000 is one of conservation biology's greatest success stories. From fewer than 200 tigers in the early 20th century to 1,008 today — a 5x increase in 30 years. Bandhavgarh alone hosts 125 tigers — the highest density in the world. The success attracted ₹800 crore in international conservation funding from WWF and UNDP, and boosted nature tourism in MP by 40%.",
    source: src.toi,
    category: 'science',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
    coordinates: { lat: 23.2599, lng: 77.4126 },
    publishedAt: hoursAgo(20),
    imageUrl: 'https://picsum.photos/seed/mp001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.93,
    impactScore: { local: 88, state: 95, national: 90, global: 85 },
    tags: ['Tigers', 'Wildlife', 'Conservation', 'Madhya Pradesh', 'Nature'],
    isBreaking: false,
    viewCount: 345000,
  },

  // ─── ASSAM ──────────────────────────────────────────────────────────────────
  {
    id: 'as-001',
    title: "Kaziranga Rhino Census: One-Horned Rhinos Hit All-Time High of 4,014",
    description: "Kaziranga National Park's rhino population hits historic peak — 70% of the world's Indian rhinos.",
    summary: "Kaziranga rhino population reaches all-time high of 4,014 — 70% of world's Indian rhinos in one protected area.",
    aiSummary: "Kaziranga's rhinoceros milestone is conservation biology's greatest success story. From fewer than 200 rhinos in the early 20th century to 4,014 today. Assam's anti-poaching unit is a global model with zero poaching in 18 consecutive months. UNESCO and IUCN cited Kaziranga as a template for large mammal conservation in developing nations.",
    source: src.toi,
    category: 'science',
    state: 'Assam',
    city: 'Guwahati',
    coordinates: { lat: 26.5775, lng: 93.1716 },
    publishedAt: daysAgo(5),
    imageUrl: 'https://picsum.photos/seed/as001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.94,
    impactScore: { local: 88, state: 92, national: 85, global: 90 },
    tags: ['Kaziranga', 'Rhino', 'Wildlife', 'Conservation', 'Assam'],
    isBreaking: false,
    viewCount: 345600,
  },

  // ─── ODISHA ─────────────────────────────────────────────────────────────────
  {
    id: 'od-001',
    title: "Odisha Becomes Steel Capital: Tata-POSCO Kalinganagar Complex Hits 25 MT Capacity",
    description: "The Kalinganagar industrial complex surpasses all competitors to become Asia's largest integrated steel complex.",
    summary: "Odisha's Kalinganagar complex reaches 25 MT steel capacity — Asia's largest — led by Tata-POSCO.",
    aiSummary: "Odisha's emergence as India's steel capital represents a dramatic industrial transformation. The Kalinganagar complex's 25 MT capacity (Tata 8MT, POSCO 12MT, JSW 5MT) produces 28% of India's steel output. The complex created 2.3 lakh direct and 8 lakh indirect jobs, lifting Jajpur district's per capita income to 3x the state average. Odisha's 60% share of India's iron ore reserves combined with Paradip deep-water port creates a structurally competitive steel ecosystem.",
    source: src.et,
    category: 'business',
    state: 'Odisha',
    city: 'Bhubaneswar',
    coordinates: { lat: 20.9374, lng: 85.8122 },
    publishedAt: daysAgo(3),
    imageUrl: 'https://picsum.photos/seed/od001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.80,
    impactScore: { local: 90, state: 95, national: 85, global: 60 },
    tags: ['Odisha', 'Steel', 'Tata', 'POSCO', 'Industry', 'Manufacturing'],
    isBreaking: false,
    viewCount: 89000,
  },

  // ─── SPORTS ─────────────────────────────────────────────────────────────────
  {
    id: 'sp-001',
    title: "India Win Test Series in Australia 3-1: Rohit Sharma Calls It 'Greatest Away Win'",
    description: 'Team India clinches Border-Gavaskar Trophy with a historic 3-1 series win in Australia.',
    summary: 'India defeat Australia 3-1 in Border-Gavaskar Trophy — most dominant away Test series win. Bumrah takes 32 wickets.',
    aiSummary: "India's 3-1 series win in Australia is a watershed moment in international cricket. Jasprit Bumrah's 32 wickets in 4 Tests broke Kapil Dev's 40-year record for most wickets by an Indian in an away series. Yashasvi Jaiswal's three centuries established him as the finest young batting talent in world cricket. The victory consolidates India's position as the undisputed #1 Test team globally.",
    source: src.ndtv,
    category: 'sports',
    state: 'Maharashtra',
    city: 'Mumbai',
    coordinates: { lat: 19.0176, lng: 72.8562 },
    publishedAt: hoursAgo(16),
    imageUrl: 'https://picsum.photos/seed/sp001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.96,
    impactScore: { local: 80, state: 80, national: 99, global: 90 },
    tags: ['Cricket', 'India', 'Australia', 'Test Series', 'BGT', 'Sports'],
    isBreaking: false,
    viewCount: 892000,
  },
  {
    id: 'sp-002',
    title: 'Neeraj Chopra Sets New Asian Record with 89.94m Throw at Zurich Diamond League',
    description: "India's golden boy sets new Asian javelin record at the prestigious Zurich Diamond League.",
    summary: 'Neeraj Chopra throws 89.94m at Zurich Diamond League — new Asian record and personal best for the Olympic champion.',
    aiSummary: "Neeraj Chopra's 89.94m throw at Zurich Diamond League is the furthest any Asian has thrown a javelin in competition. Only the 6th person in history to throw beyond 89 meters. At 27, Chopra is at the peak of his career trajectory. The achievement reinforces India's athletics program as a global force ahead of the 2028 Los Angeles Olympics.",
    source: src.ndtv,
    category: 'sports',
    state: 'Haryana',
    city: 'Panipat',
    coordinates: { lat: 29.3909, lng: 76.9635 },
    publishedAt: daysAgo(3),
    imageUrl: 'https://picsum.photos/seed/sp002/800/400',
    sentiment: 'positive',
    sentimentScore: 0.95,
    impactScore: { local: 85, state: 85, national: 99, global: 95 },
    tags: ['Neeraj Chopra', 'Javelin', 'Athletics', 'Asian Record', 'Sports'],
    isBreaking: false,
    viewCount: 567000,
  },

  // ─── HEALTH ─────────────────────────────────────────────────────────────────
  {
    id: 'hl-001',
    title: "India Develops Indigenous mRNA Vaccine: CSIR-Serum Partnership Achieves Breakthrough",
    description: "India's first homegrown mRNA vaccine platform completes Phase 3 trials with 94% efficacy.",
    summary: "India's first mRNA vaccine (NMV-001) shows 94% efficacy in 45,000-person Phase 3 trial — CSIR-Serum breakthrough.",
    aiSummary: "India's indigenous mRNA vaccine (NMV-001) is a landmark in national biopharmaceutical capability. Using lipid nanoparticle delivery technology fully designed in India, it showed 94% efficacy against XBB.1.5 and JN.1 variants in 45,000 participants across 120 sites. DCGI approval expected by Q2 2025. India can then manufacture 3 billion doses annually — positioning India as a global vaccine supplier.",
    source: src.hindu,
    category: 'health',
    state: 'Maharashtra',
    city: 'Pune',
    coordinates: { lat: 18.5500, lng: 73.9000 },
    publishedAt: daysAgo(4),
    imageUrl: 'https://picsum.photos/seed/hl001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.88,
    impactScore: { local: 75, state: 80, national: 98, global: 95 },
    tags: ['mRNA Vaccine', 'Health', 'CSIR', 'Serum Institute', 'COVID'],
    isBreaking: false,
    viewCount: 423000,
  },

  // ─── PUNJAB ─────────────────────────────────────────────────────────────────
  {
    id: 'pb-001',
    title: 'Punjab Stubble Burning Down 68%: Zero-Waste Agriculture Policy Bears Fruit',
    description: 'Punjab farmers adopt bio-decomposer and Happy Seeder technology, cutting stubble burning dramatically.',
    summary: "Punjab's stubble burning falls 68% YoY as Happy Seeder subsidies and Pusa bio-decomposer adoption scale rapidly.",
    aiSummary: "Punjab achieved a remarkable 68% reduction in paddy stubble burning. The government's ₹1,500 crore subsidy for 12,000 Happy Seeder machines plus free Pusa bio-decomposer spray drove adoption across 18 lakh acres. Downstream impact: 35% improvement in Delhi's air quality during peak stubble season. Farmers adopting zero-burning also report 8% better crop yields due to improved soil microbiome.",
    source: src.ht,
    category: 'government',
    state: 'Punjab',
    city: 'Chandigarh',
    coordinates: { lat: 30.7333, lng: 76.7794 },
    publishedAt: daysAgo(1),
    imageUrl: 'https://picsum.photos/seed/pb001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.75,
    impactScore: { local: 90, state: 88, national: 75, global: 45 },
    tags: ['Punjab', 'Stubble Burning', 'Agriculture', 'Air Quality', 'Environment'],
    isBreaking: false,
    viewCount: 78900,
  },

  // ─── BIHAR ──────────────────────────────────────────────────────────────────
  {
    id: 'br-001',
    title: 'Bihar Skill Mission: 10 Lakh Youth Trained in AI, Robotics, and Advanced Manufacturing',
    description: 'Chief Minister Nitish Kumar launches phase 3 of Bihar Skill Development Mission targeting industries of the future.',
    summary: 'Bihar enrolls 10 lakh youth in AI, robotics, and manufacturing skills through IIT-Patna and NASSCOM-partnered mission.',
    aiSummary: "Bihar's Skills Mission Phase 3 is the most significant youth employment initiative in the state's history. The ₹4,200 crore program partners with IIT-Patna, NASSCOM, and global firms like Siemens, Bosch, and Tata Technologies for placement guarantees. 78% of Phase 1 graduates secured employment within 3 months, reversing Bihar's decades-long brain drain trend.",
    source: src.ie,
    category: 'education',
    state: 'Bihar',
    city: 'Patna',
    coordinates: { lat: 25.5941, lng: 85.1376 },
    publishedAt: daysAgo(2),
    imageUrl: 'https://picsum.photos/seed/br001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.80,
    impactScore: { local: 85, state: 92, national: 70, global: 30 },
    tags: ['Bihar', 'Skills', 'Youth', 'AI', 'Employment', 'Education'],
    isBreaking: false,
    viewCount: 56700,
  },

  // ─── CRIME ──────────────────────────────────────────────────────────────────
  {
    id: 'cr-001',
    title: 'CBI Arrests 14 in ₹3,500 Crore Crypto Fraud Spanning 18 States',
    description: 'Sophisticated cryptocurrency investment fraud targeting middle-class families across India is busted.',
    summary: 'CBI arrests 14 in ₹3,500 crore crypto fraud spanning 18 states, defrauding 8 lakh victims.',
    aiSummary: "The CBI's operation against the ₹3,500 crore crypto fraud network is India's largest cryptocurrency crime bust. The syndicate operated through 47 shell companies, a WhatsApp network of 2,000 agents, and fake trading platforms mimicking legitimate exchanges. Primary masterminds used Hawala to move funds to UAE and Singapore. Victims were promised 40-80% monthly returns. Parliament is expected to fast-track the Digital Assets Regulation Bill.",
    source: src.toi,
    category: 'crime',
    state: 'Punjab',
    city: 'Chandigarh',
    coordinates: { lat: 30.7250, lng: 76.7220 },
    publishedAt: hoursAgo(18),
    imageUrl: 'https://picsum.photos/seed/cr001/800/400',
    sentiment: 'negative',
    sentimentScore: -0.72,
    impactScore: { local: 75, state: 72, national: 90, global: 50 },
    tags: ['CBI', 'Crypto Fraud', 'Crime', 'Chandigarh', 'Bengaluru'],
    isBreaking: false,
    viewCount: 289000,
  },

  // ─── POLITICS ───────────────────────────────────────────────────────────────
  {
    id: 'po-001',
    title: 'Budget 2025-26: FM Announces ₹18 Lakh Crore Infrastructure Outlay — Record High',
    description: 'Finance Minister presents Union Budget 2025-26 with record capital expenditure focusing on railways, roads, ports, and digital infra.',
    summary: 'Union Budget 2025-26 allocates record ₹18 lakh crore capex — 23% higher — for railways, roads, ports, digital infra.',
    aiSummary: "Union Budget 2025-26 is India's most infrastructure-heavy budget in independent history. Key allocations: Railways (₹3.2 lakh crore for 650 Vande Bharat trains), National Highways (₹2.8 lakh crore targeting 50 km/day), Deep-water Ports (₹85,000 crore for Vadhavan and Galathea Bay), Digital Infrastructure (₹1.2 lakh crore for 5G+, AI compute, ONDC expansion). Fiscal deficit maintained at 4.5% of GDP.",
    source: src.et,
    category: 'politics',
    state: 'Delhi',
    city: 'New Delhi',
    coordinates: { lat: 28.6100, lng: 77.2000 },
    publishedAt: daysAgo(1),
    imageUrl: 'https://picsum.photos/seed/po001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.70,
    impactScore: { local: 80, state: 80, national: 99, global: 75 },
    tags: ['Budget 2025', 'Economy', 'Finance', 'Infrastructure', 'Politics'],
    isBreaking: false,
    viewCount: 1200000,
  },
  {
    id: 'po-002',
    title: 'Lok Sabha Passes Digital India Act 2025: New Framework for AI, Social Media',
    description: "Parliament approves landmark legislation establishing India's first comprehensive AI governance regime.",
    summary: "Lok Sabha passes Digital India Act 2025 — India's first comprehensive AI regulation, replacing 25-year-old IT Act.",
    aiSummary: "The Digital India Act 2025 is India's most significant digital governance legislation. Key provisions: mandatory AI Impact Assessment for high-risk systems, 72-hour data breach notification, algorithmic accountability for platforms with 10M+ users, right to digital erasure, and .IN domain hosting for government data. The AI governance framework borrows from EU AI Act but with India-specific carve-outs for strategic sectors.",
    source: src.ie,
    category: 'politics',
    state: 'Delhi',
    city: 'New Delhi',
    coordinates: { lat: 28.6150, lng: 77.2100 },
    publishedAt: hoursAgo(22),
    imageUrl: 'https://picsum.photos/seed/po002/800/400',
    sentiment: 'neutral',
    sentimentScore: 0.10,
    impactScore: { local: 80, state: 75, national: 99, global: 70 },
    tags: ['Digital India Act', 'AI Regulation', 'Parliament', 'Technology', 'Law'],
    isBreaking: false,
    viewCount: 678000,
  },

  // ─── ENTERTAINMENT ──────────────────────────────────────────────────────────
  {
    id: 'en-001',
    title: 'Kalki 2898 AD Earns ₹1,200 Crore in Opening Week — Biggest Indian Box Office Debut',
    description: "Prabhas and Deepika Padukone's sci-fi epic becomes India's highest-grossing film in opening week history.",
    summary: "Kalki 2898 AD earns ₹1,200 crore in opening week — India's biggest box office debut ever, surpassing Baahubali 2.",
    aiSummary: "Kalki 2898 AD has redefined Indian cinema's commercial ambitions. ₹1,200 crore opening week — spanning Telugu, Hindi, Tamil, Malayalam, and Kannada versions plus international markets. Visual effects produced with ILM collaboration received global industry acclaim. International distribution in 120 countries firmly establishes Indian cinema's global commercial reach.",
    source: src.toi,
    category: 'entertainment',
    state: 'Telangana',
    city: 'Hyderabad',
    coordinates: { lat: 17.4900, lng: 78.3900 },
    publishedAt: daysAgo(7),
    imageUrl: 'https://picsum.photos/seed/en001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.92,
    impactScore: { local: 88, state: 88, national: 97, global: 80 },
    tags: ['Kalki 2898 AD', 'Box Office', 'Bollywood', 'Telugu Cinema', 'Entertainment'],
    isBreaking: false,
    viewCount: 567800,
  },

  // ─── WEATHER ────────────────────────────────────────────────────────────────
  {
    id: 'wt-001',
    title: 'IMD Predicts Above-Normal Monsoon for 2025: Farmers, Economists Cheer',
    description: 'India Meteorological Department forecasts 106% of Long Period Average rainfall for southwest monsoon 2025.',
    summary: 'IMD forecasts 106% of normal rainfall for Monsoon 2025 — above-normal outlook to boost agricultural output.',
    aiSummary: "IMD's 106% LPA forecast for Monsoon 2025 has significant economic implications. Above-normal rainfall projected to boost Kharif crop production by 8-12%, reducing food inflation. Reservoirs at 67% capacity nationally expected to fill to 95%+ by September. Agricultural economists project 4.5% growth in farm sector GDP for FY2025-26. Forecast based on favorable La Niña + positive Indian Ocean Dipole — a rare combined beneficial signal.",
    source: src.hindu,
    category: 'weather',
    state: 'Maharashtra',
    city: 'Pune',
    coordinates: { lat: 18.5200, lng: 73.8600 },
    publishedAt: daysAgo(6),
    imageUrl: 'https://picsum.photos/seed/wt001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.78,
    impactScore: { local: 80, state: 82, national: 97, global: 55 },
    tags: ['Monsoon', 'IMD', 'Weather', 'Agriculture', 'Economy'],
    isBreaking: false,
    viewCount: 456000,
  },

  // ─── JAMMU & KASHMIR ────────────────────────────────────────────────────────
  {
    id: 'jk-001',
    title: 'Kashmir Tourism Hits Record 2.5 Crore Visitors in 2024 — Dal Lake Revival Programme',
    description: "Kashmir's tourism sector achieves historic peak with 2.5 crore visitors, boosted by Dal Lake restoration and Gulmarg infrastructure.",
    summary: 'Kashmir tourism reaches all-time high of 2.5 crore visitors in 2024, driven by restoration projects and connectivity.',
    aiSummary: "Kashmir's tourism milestone of 2.5 crore visitors in 2024 is 3x the pre-2019 peak and represents the largest economic recovery story in J&K's recent history. The Dal Lake restoration programme removed 47 lakh metric tonnes of weed and restored 2 km of encroached shoreline. New air connectivity with direct flights to 18 cities, including international routes to Dubai and Kuala Lumpur, has been transformative. Tourism revenue of ₹18,000 crore directly benefits 5 lakh artisans, hoteliers, and shikara operators.",
    source: src.toi,
    category: 'business',
    state: 'Jammu and Kashmir',
    city: 'Srinagar',
    coordinates: { lat: 34.0837, lng: 74.7973 },
    publishedAt: daysAgo(4),
    imageUrl: 'https://picsum.photos/seed/jk001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.88,
    impactScore: { local: 95, state: 92, national: 70, global: 50 },
    tags: ['Kashmir', 'Tourism', 'Dal Lake', 'J&K', 'Economy'],
    isBreaking: false,
    viewCount: 234500,
  },

  // ─── HIMACHAL PRADESH ───────────────────────────────────────────────────────
  {
    id: 'hp-001',
    title: 'Himachal Pradesh Launches Organic Farming Mission: 50,000 Farmers Go Chemical-Free',
    description: '50,000 Himachal farmers certify as organic producers, targeting a premium export market worth ₹2,000 crore.',
    summary: 'Himachal Pradesh certifies 50,000 organic farmers, targeting ₹2,000 crore premium export market for apples, herbs.',
    aiSummary: "Himachal Pradesh's Organic Farming Mission has certified 50,000 farmers eliminating chemical inputs, making it the largest state-level organic agriculture program in India. The mission targets the premium export market for Himachal apples, aromatic herbs, and medicinal plants, projected at ₹2,000 crore annually. Certification under USDA Organic and EU Organic standards unlocks access to European and North American premium markets, offering farmers 40-60% price premiums over conventional produce.",
    source: src.hindu,
    category: 'government',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    coordinates: { lat: 31.1048, lng: 77.1734 },
    publishedAt: daysAgo(3),
    imageUrl: 'https://picsum.photos/seed/hp001/800/400',
    sentiment: 'positive',
    sentimentScore: 0.82,
    impactScore: { local: 90, state: 88, national: 60, global: 45 },
    tags: ['Himachal Pradesh', 'Organic Farming', 'Agriculture', 'Exports', 'Sustainability'],
    isBreaking: false,
    viewCount: 45600,
  },
];

// ─── Helper Functions ────────────────────────────────────────────────────────

export function getArticleById(id: string): NewsArticle | undefined {
  return MOCK_ARTICLES.find((a) => a.id === id);
}

export function getArticlesByState(state: IndianState): NewsArticle[] {
  return MOCK_ARTICLES.filter((a) => a.state === state);
}

export function getArticlesByCategory(category: NewsCategory): NewsArticle[] {
  return MOCK_ARTICLES.filter((a) => a.category === category);
}

export function getBreakingNews(): NewsArticle[] {
  return MOCK_ARTICLES.filter((a) => a.isBreaking);
}

export function getRecentArticles(hours = 24): NewsArticle[] {
  const cutoff = new Date(Date.now() - hours * 3600000);
  return MOCK_ARTICLES.filter((a) => new Date(a.publishedAt) >= cutoff);
}

export function searchArticles(query: string): NewsArticle[] {
  const q = query.toLowerCase();
  return MOCK_ARTICLES.filter(
    (a) =>
      a.title.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.summary.toLowerCase().includes(q) ||
      a.tags.some((t) => t.toLowerCase().includes(q)) ||
      a.state?.toLowerCase().includes(q) ||
      a.city?.toLowerCase().includes(q)
  );
}

export function getTrendingTopics() {
  const tagCounts: Record<string, number> = {};
  MOCK_ARTICLES.forEach((a) => {
    a.tags.forEach((tag) => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1;
    });
  });
  return Object.entries(tagCounts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 15)
    .map(([topic, count]) => ({ topic, count }));
}

export function getSentimentStats() {
  const total = MOCK_ARTICLES.length;
  const positive = MOCK_ARTICLES.filter((a) => a.sentiment === 'positive').length;
  const negative = MOCK_ARTICLES.filter((a) => a.sentiment === 'negative').length;
  const neutral  = MOCK_ARTICLES.filter((a) => a.sentiment === 'neutral').length;
  return {
    positive: Math.round((positive / total) * 100),
    negative: Math.round((negative / total) * 100),
    neutral:  Math.round((neutral  / total) * 100),
  };
}

export function getStateStats(): Partial<Record<IndianState, number>> {
  const stateCounts: Partial<Record<IndianState, number>> = {};
  MOCK_ARTICLES.forEach((a) => {
    if (a.state) stateCounts[a.state] = (stateCounts[a.state] || 0) + 1;
  });
  return stateCounts;
}

export const CATEGORY_COLORS: Record<NewsCategory, string> = {
  politics:      '#ef4444',
  technology:    '#3b82f6',
  startups:      '#84cc16',
  business:      '#f59e0b',
  sports:        '#10b981',
  entertainment: '#a855f7',
  education:     '#f97316',
  science:       '#14b8a6',
  weather:       '#8b5cf6',
  crime:         '#6b7280',
  health:        '#06b6d4',
  government:    '#dc2626',
};

export const CATEGORY_LABELS: Record<NewsCategory, string> = {
  politics:      'Politics',
  technology:    'Technology',
  startups:      'Startups',
  business:      'Business',
  sports:        'Sports',
  entertainment: 'Entertainment',
  education:     'Education',
  science:       'Science',
  weather:       'Weather',
  crime:         'Crime',
  health:        'Health',
  government:    'Government',
};

export const CATEGORY_ICONS: Record<NewsCategory, string> = {
  politics:      '🏛️',
  technology:    '💻',
  startups:      '🚀',
  business:      '📈',
  sports:        '🏏',
  entertainment: '🎬',
  education:     '📚',
  science:       '🔬',
  weather:       '🌧️',
  crime:         '🚨',
  health:        '🏥',
  government:    '🗳️',
};
