from datetime import datetime, timedelta
import random

def get_seed_articles():
    now = datetime.utcnow()
    
    articles = [
        {
            "id": "mh-001",
            "title": "Mumbai Metro Line 3 Fully Operational: Record 8 Lakh Daily Riders in First Week",
            "description": "The underground Aqua Line connecting Aarey to Cuffe Parade has transformed Mumbai commuting, cutting travel time from 75 to 40 minutes.",
            "content": "The underground Aqua Line connecting Aarey to Cuffe Parade has transformed Mumbai commuting, cutting travel time from 75 to 40 minutes. The ₹33,406 crore project is expected to remove 4.5 lakh cars from Mumbai roads annually.",
            "summary": "Mumbai Metro Line 3 crosses 8 lakh daily riders milestone, easing commute across the 33.5 km Aqua Line.",
            "ai_summary": "Mumbai's underground Metro Line 3 (Aqua Line) achieved unprecedented ridership of 8 lakh commuters per day in its inaugural full week. This infrastructure milestone reduces the Aarey-to-Cuffe Parade journey from 75 to 40 minutes, decongesting major arterial roads. The ₹33,406 crore project is expected to remove 4.5 lakh cars from Mumbai roads annually.",
            "source_name": "Times of India",
            "source_url": "https://timesofindia.com",
            "category": "government",
            "state": "Maharashtra",
            "city": "Mumbai",
            "latitude": 19.0760,
            "longitude": 72.8777,
            "published_at": now - timedelta(hours=2),
            "image_url": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=60",
            "url": "https://timesofindia.com/mumbai-metro-line-3-fully-operational",
            "sentiment": "positive",
            "sentiment_score": 0.82,
            "impact_local": 95,
            "impact_state": 80,
            "impact_national": 60,
            "impact_global": 15,
            "tags": "Mumbai, Metro, Infrastructure, Transport, Maharashtra",
            "is_breaking": True,
            "view_count": 45230
        },
        {
            "id": "mh-002",
            "title": "Pune Startup Ecosystem Sees ₹4,200 Crore VC Investment in Q1 2026",
            "description": "Pune's tech startup scene is booming with major investments in SaaS, fintech, and deeptech sectors.",
            "content": "Pune's tech startup scene is booming with major investments in SaaS, fintech, and deeptech sectors. The Maharashtra government's Pune Startup Hub initiative combined with proximity to Bengaluru talent pools has positioned the city as a formidable third pillar of India's innovation economy.",
            "summary": "Pune attracts ₹4,200 crore in VC investment in Q1 2026, cementing its position as India's third-largest startup hub.",
            "ai_summary": "Pune's startup ecosystem attracted ₹4,200 crore in venture capital during Q1 2026, outpacing traditional hubs. Key sectors include B2B SaaS, fintech infrastructure, and deep tech. The Maharashtra government's Pune Startup Hub initiative combined with proximity to Bengaluru talent pools has positioned the city as a formidable third pillar of India's innovation economy.",
            "source_name": "Economic Times",
            "source_url": "https://economictimes.com",
            "category": "startups",
            "state": "Maharashtra",
            "city": "Pune",
            "latitude": 18.5204,
            "longitude": 73.8567,
            "published_at": now - timedelta(hours=5),
            "image_url": "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=60",
            "url": "https://economictimes.com/pune-startup-ecosystem-vc-investment",
            "sentiment": "positive",
            "sentiment_score": 0.75,
            "impact_local": 85,
            "impact_state": 90,
            "impact_national": 70,
            "impact_global": 40,
            "tags": "Pune, Startups, Venture Capital, Technology, Maharashtra",
            "is_breaking": False,
            "view_count": 23400
        },
        {
            "id": "dl-001",
            "title": "Delhi AQI Improves to 'Moderate' as Winter Pollution Task Force Shows Results",
            "description": "Sustained enforcement of anti-pollution measures brings Delhi's AQI to a 5-year low for this season.",
            "content": "Sustained enforcement of anti-pollution measures brings Delhi's AQI to a 5-year low for this season. Delhi achieved a significant air quality milestone with AQI readings in the Moderate category (85), best performance in 5 years. Improvements stem from stubble burning reduction in Punjab and stricter vehicular checks.",
            "summary": "Delhi AQI reaches 5-year seasonal low of 85 ('Moderate') as multi-agency pollution control measures yield results.",
            "ai_summary": "Delhi achieved a significant air quality milestone with AQI readings in the Moderate category (85), best performance in 5 years. Improvements stem from: satellite-monitored stubble burning reduction in Punjab (down 42%), stricter vehicular emission checks, and GRAP enforcement. Experts caution sustained improvement requires structural changes to agricultural and industrial emissions.",
            "source_name": "The Hindu",
            "source_url": "https://thehindu.com",
            "category": "weather",
            "state": "Delhi",
            "city": "New Delhi",
            "latitude": 28.6139,
            "longitude": 77.2090,
            "published_at": now - timedelta(hours=3),
            "image_url": "https://images.unsplash.com/photo-1610214691458-7e3f28cf69d6?w=800&auto=format&fit=crop&q=60",
            "url": "https://thehindu.com/delhi-aqi-improves-to-moderate",
            "sentiment": "positive",
            "sentiment_score": 0.65,
            "impact_local": 98,
            "impact_state": 95,
            "impact_national": 60,
            "impact_global": 35,
            "tags": "Delhi, Air Quality, AQI, Pollution, Environment",
            "is_breaking": False,
            "view_count": 89000
        },
        {
            "id": "ka-001",
            "title": "Bengaluru Startup Ather Energy IPO Subscribed 47x, Raises ₹3,100 Crore",
            "description": "Electric vehicle startup Ather Energy's mega IPO sees overwhelming investor response, valuing the company at ₹22,000 crore.",
            "content": "Electric vehicle startup Ather Energy's mega IPO sees overwhelming investor response, valuing the company at ₹22,000 crore. The listing is one of the largest EV startup listings in India and signifies strong public market demand for sustainable transport ventures.",
            "summary": "Ather Energy IPO subscribed 47x, raising ₹3,100 crore — largest EV startup listing in India.",
            "ai_summary": "Bengaluru-based electric scooter manufacturer Ather Energy closed its initial public offering with a subscription rate of 47 times, raising ₹3,100 crore. The listing values the company at ₹22,000 crore, making it a benchmark event for Indian EV startup exits. Proceeds will fund their third manufacturing plant in Maharashtra and research on cell localization.",
            "source_name": "Economic Times",
            "source_url": "https://economictimes.com",
            "category": "startups",
            "state": "Karnataka",
            "city": "Bengaluru",
            "latitude": 12.9716,
            "longitude": 77.5946,
            "published_at": now - timedelta(hours=4),
            "image_url": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=60",
            "url": "https://economictimes.com/ather-energy-ipo-subscribed-47x",
            "sentiment": "positive",
            "sentiment_score": 0.9,
            "impact_local": 85,
            "impact_state": 75,
            "impact_national": 80,
            "impact_global": 50,
            "tags": "Ather Energy, Bengaluru, IPO, Electric Vehicles, Startups",
            "is_breaking": True,
            "view_count": 52400
        },
        {
            "id": "tn-001",
            "title": "Foxconn and Tamil Nadu Sign Deal for $1.5 Billion Electronics Manufacturing Expansion",
            "description": "The investment will expand the iPhone assembler's facilities near Chennai, expected to create 50,000 jobs.",
            "content": "The investment will expand the iPhone assembler's facilities near Chennai, expected to create 50,000 jobs. Foxconn is doubling down on India as part of supply chain diversification strategies.",
            "summary": "Foxconn to invest $1.5 billion in Tamil Nadu near Chennai, creating 50,000 jobs in electronics manufacturing expansion.",
            "ai_summary": "Foxconn signed an agreement with the Tamil Nadu government to invest $1.5 billion in expanding its electronics assembly campus in Sriperumbudur. This expansion focuses on smartphone manufacturing and new semiconductor packaging divisions, creating 50,000 direct jobs. This cements Tamil Nadu's position as the leading electronics exporter in India.",
            "source_name": "The Hindu",
            "source_url": "https://thehindu.com",
            "category": "business",
            "state": "Tamil Nadu",
            "city": "Chennai",
            "latitude": 13.0827,
            "longitude": 80.2707,
            "published_at": now - timedelta(hours=6),
            "image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=60",
            "url": "https://thehindu.com/foxconn-tamil-nadu-electronics-manufacturing",
            "sentiment": "positive",
            "sentiment_score": 0.85,
            "impact_local": 90,
            "impact_state": 95,
            "impact_national": 85,
            "impact_global": 70,
            "tags": "Foxconn, Tamil Nadu, Apple, Chennai, Manufacturing",
            "is_breaking": False,
            "view_count": 38100
        },
        {
            "id": "gj-001",
            "title": "World's Largest Renewable Energy Park in Gujarat's Khavda Transmits First 2,000 MW",
            "description": "Adani Green Energy commissions the first phase of the massive 30 GW solar and wind park in the Rann of Kutch.",
            "content": "Adani Green Energy commissions the first phase of the massive 30 GW solar and wind park in the Rann of Kutch. The project is crucial to India's target of reaching 500 GW of non-fossil capacity by 2030.",
            "summary": "Khavda Renewable Energy Park in Gujarat transmits first 2,000 MW to the national grid, on track for 30 GW capacity.",
            "ai_summary": "Gujarat's Khavda Renewable Energy Park commissioned its first 2,000 MW capacity, transmitting clean energy to the national grid. Spanning 726 square kilometers in the Rann of Kutch, the 30 GW project is the world's largest wind-solar hybrid installation. On completion, it will generate enough power for 1.6 crore homes, offsetting 5.8 crore tons of CO2 annually.",
            "source_name": "Hindustan Times",
            "source_url": "https://hindustantimes.com",
            "category": "science",
            "state": "Gujarat",
            "city": "Gandhinagar",
            "latitude": 23.0225,
            "longitude": 72.5714,
            "published_at": now - timedelta(days=1),
            "image_url": "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&auto=format&fit=crop&q=60",
            "url": "https://hindustantimes.com/khavda-renewable-energy-park-gujarat",
            "sentiment": "positive",
            "sentiment_score": 0.95,
            "impact_local": 80,
            "impact_state": 90,
            "impact_national": 95,
            "impact_global": 85,
            "tags": "Gujarat, Khavda, Solar, Wind, Renewable Energy",
            "is_breaking": False,
            "view_count": 48200
        },
        {
            "id": "kl-001",
            "title": "Kerala Tourism Launches 'AyurVeda Trails' Project to Boost Off-Season Wellness Travel",
            "description": "The Department of Tourism partners with certified traditional centers to offer curated wellness packages.",
            "content": "The Department of Tourism partners with certified traditional centers to offer curated wellness packages. The campaign targets European and Middle Eastern markets, aiming for a 35% increase in monsoon tourism.",
            "summary": "Kerala launches 'AyurVeda Trails' to promote monsoon tourism and traditional wellness tourism.",
            "ai_summary": "Kerala Tourism introduced the 'AyurVeda Trails' initiative, partnering with 45 certified heritage centers to promote monsoon wellness travel. The scheme offers digital trail-mapping and standardized packages to capture growing wellness tourism demand, helping offset traditional off-season drops and supporting local hospitality jobs.",
            "source_name": "Indian Express",
            "source_url": "https://indianexpress.com",
            "category": "business",
            "state": "Kerala",
            "city": "Kochi",
            "latitude": 10.8505,
            "longitude": 76.2711,
            "published_at": now - timedelta(hours=12),
            "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=60",
            "url": "https://indianexpress.com/kerala-tourism-ayurveda-trails",
            "sentiment": "positive",
            "sentiment_score": 0.7,
            "impact_local": 85,
            "impact_state": 80,
            "impact_national": 50,
            "impact_global": 45,
            "tags": "Kerala, Tourism, Ayurveda, Wellness, Monsoon",
            "is_breaking": False,
            "view_count": 18900
        },
        {
            "id": "up-001",
            "title": "Uttar Pradesh Government Allocates ₹8,000 Crore for Smart Schools in Rural Areas",
            "description": "The project will upgrade infrastructure, install digital smartboards, and train teachers in 25,000 primary schools.",
            "content": "The project will upgrade infrastructure, install digital smartboards, and train teachers in 25,000 primary schools. This is part of the UP Basic Education Department's digital transformation initiative.",
            "summary": "UP government earmarks ₹8,000 crore to turn 25,000 rural primary schools into digital 'smart schools'.",
            "ai_summary": "The Uttar Pradesh cabinet approved an ₹8,000 crore scheme to transform 25,000 primary schools in rural districts. Upgrades include broadband connectivity, solar panels, digital display panels, and updated science kits. This massive project aims to bridge the rural-urban learning divide and improve attendance rates.",
            "source_name": "Times of India",
            "source_url": "https://timesofindia.com",
            "category": "education",
            "state": "Uttar Pradesh",
            "city": "Lucknow",
            "latitude": 26.8467,
            "longitude": 80.9462,
            "published_at": now - timedelta(hours=14),
            "image_url": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=60",
            "url": "https://timesofindia.com/up-government-allocates-smart-schools",
            "sentiment": "positive",
            "sentiment_score": 0.8,
            "impact_local": 90,
            "impact_state": 95,
            "impact_national": 70,
            "impact_global": 20,
            "tags": "Uttar Pradesh, Smart Schools, Education, Digital Learning",
            "is_breaking": False,
            "view_count": 29800
        },
        {
            "id": "wb-001",
            "title": "Kolkata Book Fair Registers Record Footfall of 28 Lakh, Sales Cross ₹25 Crore",
            "description": "The 12-day international event concluded with massive enthusiasm and strong participation from international publishers.",
            "content": "The 12-day international event concluded with massive enthusiasm and strong participation from international publishers. Publications in Bengali, Hindi, and English saw exceptionally high sales.",
            "summary": "International Kolkata Book Fair concludes with 28 lakh visitors and book sales topping ₹25 crore.",
            "ai_summary": "The International Kolkata Book Fair wrapped up its latest edition, recording 28 lakh visitors and a turnover of ₹25 crore. With the UK as the theme country, the event featured 800+ stalls. The high sales highlight Kolkata's enduring literary culture despite the rise of digital reading platforms.",
            "source_name": "Indian Express",
            "source_url": "https://indianexpress.com",
            "category": "entertainment",
            "state": "West Bengal",
            "city": "Kolkata",
            "latitude": 22.5726,
            "longitude": 88.3639,
            "published_at": now - timedelta(days=2),
            "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=60",
            "url": "https://indianexpress.com/kolkata-book-fair-record-footfall",
            "sentiment": "positive",
            "sentiment_score": 0.88,
            "impact_local": 95,
            "impact_state": 85,
            "impact_national": 60,
            "impact_global": 30,
            "tags": "Kolkata, Book Fair, Literature, Culture, West Bengal",
            "is_breaking": False,
            "view_count": 34100
        },
        {
            "id": "rj-001",
            "title": "Rajasthan Solar Park in Bhadla Commissioned with Added Battery Storage Facility",
            "description": "The park, already one of the largest in the world, receives battery energy storage systems to supply power after sunset.",
            "content": "The park, already one of the largest in the world, receives battery energy storage systems to supply power after sunset. This improves grid stability and reduces reliance on coal peak power plants.",
            "summary": "Bhadla Solar Park in Rajasthan integrates battery storage to supply clean energy during peak evening hours.",
            "ai_summary": "Bhadla Solar Park in Rajasthan's Jodhpur district, the world's largest solar installation, integrated a new 500 MW Battery Energy Storage System (BESS). This allows the park to feed solar energy to the grid during evening peak hours, solving grid balancing issues and paving the way for 24/7 renewable power.",
            "source_name": "Times of India",
            "source_url": "https://timesofindia.com",
            "category": "science",
            "state": "Rajasthan",
            "city": "Jaipur",
            "latitude": 26.9124,
            "longitude": 75.7873,
            "published_at": now - timedelta(days=3),
            "image_url": "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&auto=format&fit=crop&q=60",
            "url": "https://timesofindia.com/bhadla-solar-park-battery-storage",
            "sentiment": "positive",
            "sentiment_score": 0.9,
            "impact_local": 80,
            "impact_state": 85,
            "impact_national": 95,
            "impact_global": 60,
            "tags": "Bhadla, Rajasthan, Solar, Battery Storage, Green Energy",
            "is_breaking": False,
            "view_count": 41200
        }
    ]
    
    return articles
